### ISSUE TITLE
Unclear what to fill in as region into .env

### ISSUE THREAD

**Issue by freebrowser1** [djtroyal/pia-wg#1]
When I fill in 'fr' or 'france' or 'us' or whatever in 'region' in the `.env` file I get an error.
So it is impossible to process further.
What should I fill in into region ?
```
(venv) user@ubuntu-arm:~/pia-wg$ ./venv/bin/python3 generate-config.py
Traceback (most recent call last):
  File "/home/user/pia-wg/generate-config.py", line 22, in <module>
    if pia.get_token(username, password):
  File "/home/user/pia-wg/piawg.py", line 36, in get_token
    meta_cn = self.server_list[self.region]['servers']['meta'][0]['cn']
KeyError: 'france'
(venv) user@ubuntu-arm:~/pia-wg$ 
pր,
```

**Comment by freebrowser1** [comment]
EDIT: It does work now, after I filled in in the region field, EXACTLY the name of the region as displayed in a PIA app.
E.g. "IT Milano" or "France" which should be case sensitive !
So that can be edited in the documentation.
